spring:
  config:
    import:
    - "classpath:tiles.yml"
    - "classpath:player_classes.yml"
    - "classpath:items-consumables.yml"
    - "classpath:items-weapons.yml"
    - "classpath:items-resources.yml"
game:
  tick-rate: 250
  admin-mode: true
  starting-map-id: "nadrazi-veleslavin"