spring:
  config:
    import:
      - "classpath:tiles.yml"
      - "classpath:player_classes.yml"
      - "classpath:items-consumables.yml"
      - "classpath:items-weapons.yml"
      - "classpath:items-resources.yml"
      - "classpath:npc-dialog.yml"
      - "classpath:npcs-mutants.yml"
      - "classpath:npcs-traders.yml"
      - "classpath:npcs-story.yml"
game:
  tick-rate: 500
  starting-map-id: "nadrazi-veleslavin" #placeholder
  line-id: "line_a"