spring:
  config:
    import:
    - "classpath:tiles.yml"
    - "classpath:player_classes.yml"
    - "classpath:items-consumables.yml"
    - "classpath:items-weapons.yml"
    - "classpath:items-resources.yml"
game:
  tick-rate: 250
  spawn:
    x: 42
    y: 2
    layer: 1
  starting-map-id: "nadrazi_veleslavin"